implementation first sprint.
DimaRuban/Educational_project pull request #2
Opened 2021-04-20 21:14 UTC by DimaRuban

2021-04-23 20:35 UTC, serhii-shkodenko requested changes

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +    public static class AccountController
Этот класс делает слишком много. Он выводит информацию на экран, делает проверку данных, непосредственно работает с хранилищем данных. Он должен иметь зависимости, которые делают эту работу и делают это хорошо, тогда он будет соответтствовать Single Responsibility Principle. Поэтому этот класс не может быть статическим.

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +    public static class OrderController
Этот класс делает слишком много. Он выводит информацию на экран, делает проверку данных, непосредственно работает с хранилищем данных. Он должен иметь зависимости, которые делают эту работу и делают это хорошо, тогда он будет соответтствовать Single Responsibility Principle. Поэтому этот класс не может быть статическим.

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +        public static decimal  totalPriceOrder { get; set; }
В статических свойствах нельзя хранить состояние, это не потокобезопасно.

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +    {
Этот класс делает слишком много. Он выводит информацию на экран, делает проверку данных, непосредственно работает с хранилищем данных. Он должен иметь зависимости, которые делают эту работу и делают это хорошо, тогда он будет соответтствовать Single Responsibility Principle. Поэтому этот класс не может быть статическим.

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +            try {
Нет нужды весь код оборачивать в блок try. Я на встрече об этом говорил.

2021-04-23 20:35 UTC, serhii-shkodenko commented on Educational_project/DbContext.cs
> +        public static List<Product> products = new List<Product>();
Поля класса не могут быть публичными.

2021-05-04 13:39 UTC, serhii-shkodenko requested changes
Классы, которые содержат в своем названии слово `controller` по-прежнему делают несвойственные им функции и противоречат Single responsibility principle. Их нужно разделить на сущности, которые управляют бизнес объектами и пользовательским интерфейсом.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<Product> products { get; set; }
Модификаторы `public` в интерфейсах избыточны. По умолчанию, члены интерфейсов все публичные. Его лучше удалить.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<Order> orders { get; set; }
Модификаторы `public` в интерфейсах избыточны. По умолчанию, члены интерфейсов все публичные. Его лучше удалить.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<User> users { get; set; }
Модификаторы `public` в интерфейсах избыточны. По умолчанию, члены интерфейсов все публичные. Его лучше удалить.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<Product> products { get; set; }
Имя свойств согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) должны быть в `PascalCase`.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<Order> orders { get; set; }
Имя свойств согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) должны быть в `PascalCase`.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IDbContext.cs
> +        public List<User> users { get; set; }
Имя свойств согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) должны быть в `PascalCase`.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +            var productController = new ProductController(dbContext, logger);
Эта зависимость должна быть внедрена через конструктор.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +            var orderController = new OrderController(dbContext, logger, productController);
Эта зависимость должна быть внедрена через конструктор.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +            var accountController = new AccountController(dbContext, logger, validator);
Эта зависимость должна быть внедрена через конструктор.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +    public static class Menu
После внедрения зависимостей модификатор `static` придется удалить.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +        public static  void GetMenu()
После внедрения зависимостей модификатор static придется удалить.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/Program.cs
> +            while (true)
Нужно добавить возможность выхода из цикла.

2021-05-04 13:39 UTC, serhii-shkodenko commented on Educational_project/UI/Logger.cs
> +    public class Logger : ILogger
Этот класс на самом деле выполняет функции взаимодействия с пользователем, а не логированя, поэтому должен быть назван соответвующим образом.

2021-05-04 22:30 UTC, serhii-shkodenko commented
Этот ПР содержит как второе задание, так и третье. Раздели его на два. Если бы это было сделано, второе задание было бы уже сдано.

2021-05-05 03:22 UTC, DimaRuban commented
Здравствуйте, здесь я немного не понял)
Я же сдал 2-е задание и замержил его в главную ветку и на основе его делал 3-е.
Выходит, что я его не сдал и что мне необходимо сделать?

2021-05-05 05:31 UTC, serhii-shkodenko commented
> Этот ПР содержит как второе задание, так и третье. Раздели его на два. Если бы это было сделано, второе задание было бы уже сдано.

2021-05-05 05:35 UTC, serhii-shkodenko commented
> Здравствуйте, здесь я немного не понял)
> Я же сдал 2-е задание и замержил его в главную ветку и на основе его делал 3-е.
> Выходит, что я его не сдал и что мне необходимо сделать?

Да, ты прав. Второе задание ты сдал. Ты все правильно сделал. Однако первое задание не сдано, для него попросту нет ПР.

2021-05-05 20:24 UTC, serhii-shkodenko commented
Отметь, пожалуйста, исправленными те замечания, которые ты поправил. Для этого служит кнопка "Resolve conversation".

2021-05-05 20:27 UTC, serhii-shkodenko requested changes
В целом значительно лучше. Но есть еще что поправить.

2021-05-05 20:27 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +        public AccountController(IDbContext dbContext, IValidator validator, IAccountUi accountUi)
Этот констроллера должен вызываться из UI, а не наоборот. Просмотри весь ПР, пожалуйста, и поправь.

2021-05-06 04:13 UTC, DimaRuban commented on Educational_project/Controllers/AccountController.cs
> +        public AccountController(IDbContext dbContext, IValidator validator, IAccountUi accountUi)
Вы имеете ввиду, что необходимо AccountController  вызывать через AccountUi, либо Validator через AccountUi?

2021-05-06 08:54 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +        public AccountController(IDbContext dbContext, IValidator validator, IAccountUi accountUi)
>Вы имеете ввиду, что необходимо AccountController вызывать через AccountUi, либо Validator через AccountUi?

Да, AccountController должен вызываться из AccountUi. Обычно резолвят комменты, когда запушат изменения, в которых эти замечания были поправлены.

2021-05-15 23:32 UTC, serhii-shkodenko requested changes

2021-05-15 23:32 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +            int newUserId = _dbContext.Users.Count + 1;
Эта логика опеределения Id приведет к ошибкам. Рассмотрим следующий сценарий.

Исходное состояние хранилища:
```
User { Id = 1 };
User { Id = 2 };
User { Id = 3 };
```

Удалим объект с Id == 2. Сотояние хранилища после удаления:
```
User { Id = 1 };
User { Id = 3 };
```

Добавляем новый объект. Состояние после добавления:
```
User { Id = 1 };
User { Id = 3 };
User { Id = 3 };
```

Как видишь ошибки, неизбежны. Посмотри в сторону метода `Max()` из `System.Linq`.

2021-05-15 23:32 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +             int newOrderId = _dbContext.Orders.Count + 1;
Эта логика опеределения Id приведет к ошибкам. Рассмотрим следующий сценарий.

Исходное состояние хранилища:
```
Order { Id = 1 };
Order { Id = 2 };
Order { Id = 3 };
```

Удалим объект с Id == 2. Сотояние хранилища после удаления:
```
Order { Id = 1 };
Order { Id = 3 };
```

Добавляем новый объект. Состояние после добавления:
```
Order { Id = 1 };
Order { Id = 3 };
Order { Id = 3 };
```

Как видишь ошибки, неизбежны. Посмотри в сторону метода `Max()` из `System.Linq`.

2021-05-15 23:32 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +        public string Adress { get; set; }
Опечатка. В слове `Address` две `d`.

2021-05-15 23:32 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +        public int IdProductForBuy { get; set; }
Этих свойств не должно быть в этом классе. Он отвечает за обработку бизнесс логики. А, получается, он еще и хранит какое-то промежуточное состояние, что нарушает Single responsibility principle. Если тебе нужны каке-то данные для работы, то не храни их в этом классе, а передавай в метод в качестве аргументов.

2021-05-15 23:32 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +        public string NewProductName { get; set; }
Этих свойств не должно быть в этом классе. Он отвечает за обработку бизнесс логики. А, получается, он еще и хранит какое-то промежуточное состояние, что нарушает Single responsibility principle. Если тебе нужны каке-то данные для работы, то не храни их в этом классе, а передавай в метод в качестве аргументов.

2021-05-20 22:39 UTC, serhii-shkodenko commented
Поправь комментарии, которые ты поправил, как поправленные. Если ты с чем-то несогласен, укажи это и не резолви этот комментарий.

2021-05-21 19:33 UTC, serhii-shkodenko requested changes

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +        private readonly Order _order;
Тебе этот объект нужен только чтобы почитать заказ и выставить счет. Поэтому его слудет передвать не в контруктор, а аргуметов в параметр метода `Buy()`.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +             switch (_order.ConfirmButton)
Этот метод определен в слое бизнес логики, а поэтому не должен содержать сслылок на слой UI. У тебя получается, что модель в хранилище знает, о некой кнопке из UI и помнит ее значение заданное пользователем и на основании этого ты строишь бизнес логику. 

Этот метод лучше всего переписать, удалив у класса `Order` свойство `ConfirmButton`, удалив также `switch`. Логику вызова этого метода в зависимости от выбора пользователя стоит оставить в классе из слоя UI.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +            DateTime dateTimeCreatedOrder = DateTime.Now;
Эту переменную лучше удалить и использовать в нужном месте сразу `DateTime.Now`.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +        private readonly Product _product;
Этот объект следует передавать прямо в метод `AddNewProduct()` в виде аргумента, а это поле - удалить.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +        public ProductController(IDbContext dbContext, Product product)
Зависимость `Product` лушче удалить. См. также выше комментарий.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Program.cs
> +            var user = new User();
Этот пустой объект лучше удалить.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Program.cs
> +            var order = new Order();
Этот пустой объект лучше удалить.

2021-05-21 19:33 UTC, serhii-shkodenko commented on Educational_project/Program.cs
> +            var product = new Product();
Этот пустой объект лучше удалить.

2021-06-02 17:35 UTC, serhii-shkodenko requested changes
В целом неплохо, но есть что поправить еще.

2021-06-02 17:35 UTC, serhii-shkodenko commented on Educational_project/UI/Display.cs
> +        public void PrintForDisplay(string message)
Нет нужды дублировать имя класса в имени метода. Достаточно будет просто `Print()`.

2021-06-02 17:35 UTC, serhii-shkodenko commented on Educational_project/UI/OrderUi.cs
> +                foreach (var product in _dbContext.Products)
Этот класс у тебя отвечает за UI и не должен знать про хранилище. Вынеси часть этого метода в класс бизнесс логики, используй этот метод, а здесь уже заверши вывод на консоль. Зависимость от хранилища не забудь удалить.

2021-06-02 17:35 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IValidator.cs
> +            return true;
Лучше вынести это в реализацию.

2021-06-02 17:35 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IValidator.cs
> +        void CheckingPhoneNumber(string message) { }
Оставь здесь только контракты. Удали, пожалуйста, реализации.

2021-06-02 17:35 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IValidator.cs
> +        void CheckingHomeAdrress(string message) { }
Тип `void` в методах валидации смотрится не очень оптимально, лучше чтобы они возвращали `bool`. И обычно такие методы называюся так, чтобы в имени было слово или `Is` или `Has`. Возможно, этот конкретно метод лучше назвать `IsAddressValid()`.

2021-06-02 17:49 UTC, DimaRuban commented on Educational_project/Сontracts/IValidator.cs
> +        void CheckingHomeAdrress(string message) { }
Это заглушки, я их переопределяю в 4 задании уже.

2021-06-02 18:05 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IValidator.cs
> +        void CheckingHomeAdrress(string message) { }
Вот каким должен быть интерфейс этот: 

void IsAddressValid(string message);
void IsPhoneNumberValid(string message);

Обрати внимание на написание слова `address`.

2021-06-02 18:24 UTC, serhii-shkodenko requested changes

2021-06-02 18:24 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +        public string ChoiceProduct(int idProductForBuy)
Этот метод лучше назвать `GetNameForProductId(int id)`.

2021-06-02 18:24 UTC, serhii-shkodenko commented on Educational_project/Controllers/OrderController.cs
> +            foreach (var product in _dbContext.Products)
Вот так лучше будет:

`return _dbContext.Products.FirstOrDefault(x=>x.Id == id)?.Name;`

2021-06-02 18:40 UTC, serhii-shkodenko requested changes

2021-06-02 18:40 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +            int newProductId = _dbContext.Products.Max(x => x.Id) + 1;
Используй `var`.

2021-06-02 18:40 UTC, serhii-shkodenko commented on Educational_project/UI/OrderUi.cs
> +        public void ChoiceProductUi()
Имя метода должно содержать глагол.

2021-06-02 18:40 UTC, serhii-shkodenko commented on Educational_project/UI/ProductUi.cs
> +            _dbContext.InitData();
Сделай инициализацию в методе `Main`, когда создаешь хранилище. Эту зависимость из этого класса лучше удалить.

2021-06-02 18:40 UTC, serhii-shkodenko commented on Educational_project/Validation/Validator.cs
> +        public bool CheckingUserName(string userName)
1. Этот метод лучше назвать `IsUserExists()`. 
2. Этот метод должен находится в бизнес слое, отвечающем за добавление/удалание пользователей. 
3. Зависимости от `IDisplay` быть не должно. 
4. Получается пока этот класс тебе не нужен.

2021-06-02 18:40 UTC, serhii-shkodenko commented on Educational_project/Validation/Validator.cs
> +                    _display.Print("\nЭто имя пользователя уже занято, выберете другое!\n");
Будет достаточно проверить, и пусть слой UI уже решает, что ему выводить.

2021-06-02 18:49 UTC, serhii-shkodenko requested changes

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +        public void Registration(string firstName, string lastName, string emailAddress, string phoneNumber, string userName, string password)
Имя метода [должно содержаить глагол](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods). Поэтому будет лучше `Register()`.

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/Controllers/ProductController.cs
> +        public void AddNewProduct(string name, decimal price, string color, int memorySize)
Достаточно будет назвать просто `AddProduct()`.

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/UI/AccountUi.cs
> +        public string FirstName { get; set; }
А почему это публичные свойства, а не приватные переменные?

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/UI/AccountUi.cs
> +        public void RegistrationUi()
Имя метода должно [содержать глагол](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/UI/Menu.cs
> +        void OutMenu ()
Не хватает модификатора доступа.

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/UI/OrderUi.cs
> +        public void BuyUi()
Звучит, как "Купить пользовательский интерфейс". Лучше дать этому методу другое название.

2021-06-02 18:49 UTC, serhii-shkodenko commented on Educational_project/UI/ProductUi.cs
> +        public string Name { get; set; }
Почему это публичные свойства, а не приватные поля?

2021-06-03 20:18 UTC, serhii-shkodenko requested changes
Почти все хорошо, остались пока некоторые шероховатости.

2021-06-03 20:18 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +            string role = "User";
Если эта роль не меняется, то лучше вынести ее в приватную константу и использовать сразу в строке 21.

2021-06-03 20:18 UTC, serhii-shkodenko commented on Educational_project/Validation/Validator.cs
> +            foreach (var user in _dbContext.Users)
Эту часть кода можна вынести в место, где создается пользователь и там проверять. Или там же сделать приватный метод и исспользоваться там. Нет смысла создавать для этого целый класс и передвать ему зависимость от хранилища. У тебя уже есть место, где у тебя используется эта зависимость, там ее и используй.

2021-06-03 20:18 UTC, serhii-shkodenko commented on Educational_project/Сontracts/IAccountController.cs
> +        void Register(string firstName, string lastName, string emailAddress, string phoneNumber, string userName, string password) { }
Вот в этом методе как раз нужно сделать проверку, о которой я писал выше.

2021-06-03 20:58 UTC, serhii-shkodenko requested changes
Нашел ошибки в логике. Нужно поправить.

2021-06-03 20:58 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +                    return false;
Почему твой методу возвращает false, если пользователь существует? Должно быть наоборот.

2021-06-03 20:58 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +            foreach (var user in _dbContext.Users)
Цикл здесь не нужен, достаточно:
`return _dbContext.Users.Any(user=>user.UserName == userName);`

2021-06-03 20:58 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +            if (IsUserExists(userName) == true)
Логака должна быть обратной, если нет такого пользователя, то создаем. И можно упросить выражение:
`If (!IsUserExists(userName))`

2021-06-03 20:58 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +        private readonly string role = "User";
Здесь будет оптимальнее использоват константу. Не забудь применить правила именования для констант.

2021-06-03 21:08 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-03 21:12 UTC, merged