Implement sixth task
DimaRuban/Educational_project pull request #7
Opened 2021-05-26 19:39 UTC by DimaRuban

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Controllers/AccountController.cs
>      {
please add emty line before ctor and between methods
in all files

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Controllers/AccountController.cs
> +        private string _role = "User";
add "readonly" or rename to "role"

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/FileManager.cs
> +        private char _pathSeparator = Path.DirectorySeparatorChar;
add "readonly" or remove "_"

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/FileManager.cs
> +            using (StreamWriter streamWriter = new StreamWriter(filePath, true, Encoding.UTF8))
seems like can use "var"

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/FileManager.cs
> +                using (FileStream fstream = new FileStream(serializationProductsPath, FileMode.OpenOrCreate)) { }
verify logic
empty - it is strange

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/FileManager.cs
> +            using (StreamWriter streamWriter = new StreamWriter(serializationProductsPath, true, Encoding.UTF8))
seems like can use "var"

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/Serializer.cs
> +        private string _directoryPath = Directory.GetCurrentDirectory() + Path.DirectorySeparatorChar + "Store Phone system files" + Path.DirectorySeparatorChar;
use "readonly" or remove "_"
please verify all variables which starts from "_"

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/Serializer.cs
> +            foreach (var item in products)
maybe better use "product" name

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/Serializer.cs
> +            List<Product> products = JsonConvert.DeserializeObject<List<Product>>(File.ReadAllText(serializationProductsPath));
seems like can be var

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Logging/Serializer.cs
> +            foreach (var item in users)
maybe user

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Сontracts/ISerializer.cs
> +        void DeSerializeProducts();
Deserialize

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Сontracts/ISerializer.cs
> +        void DeSerializeOrders();
Deserialize

2021-06-06 20:53 UTC, yevhenbilushko commented on Educational_project/Сontracts/ISerializer.cs
> +        void DeSerializeUsers();
Deserialize

2021-06-06 20:54 UTC, yevhenbilushko approved these changes

2021-06-06 20:54 UTC, yevhenbilushko commented
approved
get approve from Sergey and merge

2021-06-10 14:57 UTC, serhii-shkodenko requested changes
Нужно доработать систему зависимостей для сохранения состояния хранилища. Для вызывающего кода, то есть классов с бизнес логикой, не должно ничего поменяться, по-большому счету. Новых зависимостей, вроде класса `Serializer`, быть не должно. То что под капотом происходит сохранение хранилища на диск, не должно быть известно бизнес слою.

Поэтому:
1. Удали зависимость твоего бизнес слоя от от `ISerializer`.
2. Сделай инъекцию в конструктор хранилища объекта `IFileManager`.
3. В хранилище добавь метод Save(), из которого используй методы из `IFileManager`.
4. В методах бизнес слоя при изменения хранилища добавь вызов метода `Save()`.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Controllers/AccountController.cs
> +        private string role = "User";
Еще бы `const` добавить.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +        private char pathSeparator = Path.DirectorySeparatorChar;
Нет нужды отдельно выносить это статическое поле в переменную. Сразу пользуйся в нужном месте `Path.DirectorySeparatorChar`.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +                using (var fileStream = new FileStream(filePath, FileMode.OpenOrCreate)) { }
Ты же вверху проверил, что файл не существует, а здесь допускаешь возможность, что он может быть открыт.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +        public void WorkWithSerializationFile(string message, string serializationPath)
У тебя класс называется `FileManager`, а в имени этого метода идет речь о сериализации. Лучше уратьэ то несоответствие, а метод назвать покороче, например, `Write()`. Параметр `serializationPath` тоже лучше сократить до `path`, какого рода там хранятся файлы - это детали реализации.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            var serializationProductsPath = GetDirectoryPath() + pathSeparator + serializationPath;
То же замечание, что и вверху. Лучше убрать упоминаие про сериализацию в имени переменной.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
>          public void WorkWithFiles(string message)
Метод можно назвать покороче, например, `Write()`.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return Directory.GetCurrentDirectory() + pathSeparator + "Store Phone system files";
Добавь хоть какое-то расширение в имя файла.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +                using (var fileStream = new FileStream(serializationProductsPath, FileMode.OpenOrCreate)) { }
Используй новый синтаксис using statement.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            using (var streamWriter = new StreamWriter(serializationProductsPath, false, Encoding.UTF8))
Используй новый синтаксис using statement.

2021-06-10 14:57 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +                using (var fileStream = new FileStream(serializationProductsPath, FileMode.OpenOrCreate)) { }
Зачем тебе `FileStream`, если ниже у тебя уже есть `StreamWriter`?

2021-06-10 17:25 UTC, DimaRuban commented on Educational_project/Logging/FileManager.cs
> +            return Directory.GetCurrentDirectory() + pathSeparator + "Store Phone system files";
Это название папки, где хранятся файлы.

2021-06-10 17:26 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return Directory.GetCurrentDirectory() + pathSeparator + "Store Phone system files";
Тогда вынеси его в константу.

2021-06-10 20:52 UTC, serhii-shkodenko commented
Поправь мерж конфликты.

2021-06-10 21:00 UTC, serhii-shkodenko requested changes
Исправь эти замечания, пожалуйста, и будет апрув.

2021-06-10 21:00 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return GetDirectoryPath() + Path.DirectorySeparatorChar + "Serialization Orders.txt";
Вынеси, пожалуйста, строку  "Serialization Orders.txt" в приватную константу.

2021-06-10 21:00 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return GetDirectoryPath() + Path.DirectorySeparatorChar + "Serialization Users.txt";
Вынеси, пожалуйста, строку "Serialization Users.txt" в приватную константу.

2021-06-10 21:00 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return Directory.GetCurrentDirectory() + Path.DirectorySeparatorChar + "Store Phone system files";
Вынеси, пожалуйста, строку  "Store Phone system files" в приватную константу.

2021-06-10 21:00 UTC, serhii-shkodenko commented on Educational_project/Logging/FileManager.cs
> +            return GetDirectoryPath() + Path.DirectorySeparatorChar + "Serialization Products.txt";
Вынеси, пожалуйста, строку "Serialization Products.txt" в приватную константу.

2021-06-10 21:17 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-10 21:53 UTC, merged