implement first task
DimaRuban/Educational_project pull request #8
Opened 2021-05-27 17:20 UTC by DimaRuban

2021-06-06 20:36 UTC, yevhenbilushko commented on Delivery discount/HomeWork.cs
> +        private static IEnumerable<decimal> NormalizeCurrencies(IEnumerable<decimal> prices, IEnumerable<string> currencies)
seems like "static" can be removed in all methods

2021-06-06 20:37 UTC, yevhenbilushko submitted a review, later dismissed

2021-06-06 20:38 UTC, yevhenbilushko commented
approved
get approve from Sergey and merge

2021-06-07 20:57 UTC, serhii-shkodenko requested changes

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var infantsIdsList = infantsIds.ToList();
Тебе тут не нужен лист, для цикла foreach достаточно `IEnumerable<T>`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var childrenIdsList = childrenIds.ToList();
Тебе тут не нужен лист, для цикла foreach достаточно `IEnumerable<T>`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var destinationList = destinations.ToList();
Тебе тут не нужен лист, для цикла foreach достаточно `IEnumerable<T>`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var deliveryPrice = NormalizeCurrencies(prices, currencies).ToList();
Лучше `deliveryPrices`, ведь речь идет о коллекции.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var streetNames = GetStreetName(destinations).ToList();
Вызов `ToList()` здесь неоправдан. Ты не пользуешься ничем, что дает создание нового списка.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            deliveryPrice = ApplyStreetDiscount(streetNames, deliveryPrice).ToList();
Вызов `ToList()` здесь неоправдан. В параметрах метода ты просишь `IEnumerable`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            deliveryPrice = ApplyDiscountForKids(infantsIds, childrenIds, deliveryPrice).ToList();
Вызов `ToList()` здесь неоправдан. В параметрах метода ты просишь `IEnumerable`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            deliveryPrice = ApplySameStreetDiscount(streetNames, deliveryPrice).ToList();
Вызов `ToList()` здесь неоправдан. В параметрах метода ты просишь `IEnumerable`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +            var deliveryPrice = NormalizeCurrencies(prices, currencies).ToList();
Вызов `ToList()` здесь неоправдан. В параметрах метода ты просишь `IEnumerable`.

2021-06-07 20:57 UTC, serhii-shkodenko commented on Delivery discount/HomeWork.cs
> +
А вот здесь можно сделать вызов `ToList()`, то есть сделать равно там, где он тебе нужен.

2021-06-08 18:05 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-08 18:12 UTC, merged